import { useDispatch, useSelector } from "react-redux";

import { BiUserPlus, BiX } from "react-icons/bi";
import Form from "@/components/Agents/Form";
import Head from "next/head";
import Table from "@/components/Agents/Table";
import {
  rChangeEmpID,
  rDeleteAgent,
  rToggleChangeAction,
} from "@/redux/Agents/agentSlice";
import { useState } from "react";
import { deleteAgent, getAgents } from "@/lib/helper";
import { useMutation, useQueryClient } from "react-query";

export default function Home() {
  const dispatch = useDispatch();
  const deleteId = useSelector((state: any) => state.agents.client.deleteId);
  const queryClient = useQueryClient();

  const submitHandler = () => {
    dispatch(rToggleChangeAction(null));
  };

  const deleteMutation = useMutation(() => deleteAgent(deleteId), {
    onSuccess: async () => {
      queryClient.prefetchQuery("agents", getAgents);
      await dispatch(rDeleteAgent(null));
    },
  });

  const deleteHandler = async () => {
    await deleteMutation.mutate();
  };

  const cancelHandler = async () => {
    await dispatch(rDeleteAgent(null));
  };
  const state = useSelector((state: any) => state.agents.client.toggleForm);

  return (
    <section>
      <Head>
        <title>CRUD APPLICATION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-5">
        <h1 className="text-3xl md:text-5xl text-center font-bold py-10">
          Agent Management
        </h1>
        <div className="container mx-auto flex justify-between p-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={submitHandler}
              className="flex bg-indigo-500 text-white px-5 py-2 border rounded-md hover:bg-gray-500 hover:border-indigo-500 hover:text-indigo-50"
            >
              Add Agent
              <span className="px-1 ml-2">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
            {deleteId && DeleteComponent({ deleteHandler, cancelHandler })}
          </div>
        </div>

        <div className="container mx-auto py-5">{state && <Form></Form>}</div>
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}

function DeleteComponent({ deleteHandler, cancelHandler }: any) {
  return (
    <div className="flex gap-5">
      <p>Are You Sure?</p>
      <button
        onClick={deleteHandler}
        className="flex bg-red-500 text-white px-4 py-2 board rounded-md hover:bg-rose-400 hover:border-red-500 "
      >
        yes
        <span className="px-1">
          <BiX color="rgb(255,255,255)" size={25} />
        </span>
      </button>
      <button
        onClick={cancelHandler}
        className="flex bg-green-500 text-white px-4 py-2 board rounded-md hover:bg-rose-500 hover:border-red-500"
      >
        No
      </button>
    </div>
  );
}
