import { useDispatch, useSelector } from "react-redux";

import { BiUserPlus } from "react-icons/bi";
import Head from "next/head";

import Shift from "@/components/Shifts/Shift";
import Shift_New from "@/components/Shifts/Shift_New";
import { toggleChangeAction } from "@/redux/Shift/shiftSlice";

export default function ShiftPage() {
  const dispatch = useDispatch();

  const submitHandler = () => {
    dispatch(toggleChangeAction(null));
  };

  const state = useSelector((state: any) => state.shifts.client.toggleForm);

  return (
    <section>
      <Head>
        <title>CRUD APPLICATION</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="py-5">
        <h1 className="text-3xl md:text-5xl text-center font-bold py-10">
          Shifts Management
        </h1>
        <div className="container mx-auto flex justify-between p-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={submitHandler}
              className="flex bg-indigo-500 text-white px-5 py-2 border rounded-md hover:bg-gray-500 hover:border-indigo-500 hover:text-indigo-50"
            >
              Add Shift
              <span className="px-1 ml-2">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
          </div>
        </div>

        <div className="container mx-auto py-5">
          {state && <Shift_New></Shift_New>}
        </div>
        <div className="container mx-auto">
          <Shift></Shift>
        </div>
      </main>
    </section>
  );
}
